#!/usr/bin/env python3
"""Query and maintain the learning-garden tag system.

Examples:
  ./scripts/tag list
  ./scripts/tag dns
  ./scripts/tag find dns ruby
  ./scripts/tag open dns
  ./scripts/tag untagged
  ./scripts/tag index
  ./scripts/tag autotag new-note.md
  ./scripts/tag autotag --all
  ./scripts/tag --tag dns --tag ruby
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = ROOT / "tags" / "index.md"
SYSTEM_FILES = {
    ROOT / "AGENTS.md",
    ROOT / "CLAUDE.md",
    ROOT / "TAGS.md",
    ROOT / "start.md",
    ROOT / "templates" / "note.md",
    INDEX_PATH,
}
SUFFIXES = {".md", ".txt"}

INLINE_TAGS = re.compile(r"^tags:\s*(.+?)\s*$", re.IGNORECASE)
TAG_LINE_ONLY = re.compile(r"^tags:\s*$", re.IGNORECASE)
BULLET_TAG = re.compile(r"^\s*-\s*(.+?)\s*$")


def content_files() -> list[Path]:
    files = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if any(part.startswith(".") for part in rel.parts):
            continue
        if path in SYSTEM_FILES:
            continue
        if path.suffix.lower() not in SUFFIXES:
            continue
        files.append(path)
    return files


def normalize_tag(value: str) -> str:
    value = value.strip().strip('"').strip("'").lower()
    value = value.replace("_", "-").replace(" ", "-")
    return re.sub(r"-+", "-", value)


def parse_tags(path: Path) -> list[str]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return []

    if not lines or lines[0].strip() != "---":
        return []

    end = None
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            end = index
            break
    if end is None:
        return []

    tags: list[str] = []
    collecting = False
    for line in lines[1:end]:
        inline = INLINE_TAGS.match(line)
        if inline and not TAG_LINE_ONLY.match(line):
            value = inline.group(1).strip()
            if value.startswith("[") and value.endswith("]"):
                value = value[1:-1]
            tags.extend(
                tag
                for tag in (normalize_tag(item) for item in value.split(","))
                if tag
            )
            collecting = False
            continue

        if TAG_LINE_ONLY.match(line):
            collecting = True
            continue

        if collecting:
            bullet = BULLET_TAG.match(line)
            if bullet:
                tag = normalize_tag(bullet.group(1))
                if tag:
                    tags.append(tag)
                continue
            if line.strip() and not line.startswith(" "):
                collecting = False

    seen: set[str] = set()
    return [tag for tag in tags if not (tag in seen or seen.add(tag))]


def note_title(path: Path) -> str:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return path.stem

    start = 0
    if lines and lines[0].strip() == "---":
        for index in range(1, len(lines)):
            if lines[index].strip() == "---":
                start = index + 1
                break

    for line in lines[start:]:
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def print_note(path: Path, tags: list[str]) -> None:
    rel = path.relative_to(ROOT)
    print(rel)
    if tags:
        print(f"  tags: {', '.join(tags)}")
    else:
        print("  tags: (none)")


def list_tags(notes: list[tuple[Path, list[str]]]) -> None:
    counts = Counter(tag for _, tags in notes for tag in tags)
    for tag, count in sorted(counts.items()):
        print(f"{tag}\t{count}")


def print_command_help() -> None:
    print("usage: tags <command> [options]")
    print()
    print("Commands:")
    print("  list       List all tags and their note counts")
    print("  find       Find notes matching one or more tags")
    print("  open       Pick and open a matched note in Zed")
    print("  autotag    Infer tags from path, filename, and title")
    print("  check      Verify every content note has tags")
    print("  untagged   List content notes without tags")
    print("  index      Regenerate tags/index.md")
    print("  help       Show this help")
    print()
    print("You can also use a tag name directly, e.g. `tags dns`.")


def write_index(notes: list[tuple[Path, list[str]]]) -> None:
    by_tag: dict[str, list[Path]] = {}
    for path, tags in notes:
        for tag in tags:
            by_tag.setdefault(tag, []).append(path)

    lines = [
        "# Tag Index",
        "",
        "> Generated by `python3 scripts/tags.py --index`; edit notes, not this file.",
        "",
        "## Tags",
        "",
    ]
    for tag, paths in sorted(by_tag.items()):
        lines.append(f"- `{tag}` ({len(paths)})")

    lines.extend(["", "## Notes by Tag", ""])
    for tag in sorted(by_tag):
        paths = by_tag[tag]
        lines.append(f"### `{tag}` ({len(paths)})")
        lines.append("")
        for path in paths:
            rel = path.relative_to(ROOT).as_posix()
            lines.append(f"- [{note_title(path)}]({rel})")
        lines.append("")

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text("\n".join(lines).strip() + "\n", encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(ROOT)}")


def launch_zed(path: Path) -> int:
    zed = shutil.which("zed")
    if not zed:
        zed = "/Applications/Zed.app/Contents/MacOS/zed"
    if not Path(zed).exists():
        print("Zed CLI not found")
        return 1

    rel = path.relative_to(ROOT)
    subprocess.run([zed, str(path)], check=True)
    print(f"opened {rel}")
    return 0


def open_note(paths: list[Path]) -> int:
    if not paths:
        print("No notes match")
        return 1

    if len(paths) == 1:
        return launch_zed(paths[0])

    if not shutil.which("fzf"):
        print("fzf is required to pick among multiple results")
        return 1

    choices = []
    for path in paths:
        rel = path.relative_to(ROOT).as_posix()
        choices.append(f"{rel}\t{note_title(path)}")

    result = subprocess.run(
        [
            "fzf",
            "--delimiter=\t",
            "--with-nth=2..",
            "--prompt=Open note > ",
        ],
        input="\n".join(choices) + "\n",
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        return 0

    selected = result.stdout.strip()
    if not selected:
        return 0

    rel = selected.split("\t", 1)[0]
    return launch_zed((ROOT / rel).resolve())


def infer_tags(path: Path) -> list[str]:
    rel = path.relative_to(ROOT).as_posix().lower()
    title = note_title(path).lower()
    haystack = f"{rel} {title}"

    tags: set[str] = set()

    if rel.startswith("computer/"):
        tags.add("computer-science")
    elif rel.startswith("book/"):
        tags.update(["book-notes", "reading-notes"])
    elif rel.startswith("english/"):
        tags.add("english-writing")

    keyword_rules = [
        ("dns", ["dns", "networking"]),
        ("redis", ["redis", "databases"]),
        ("postgresql", ["postgresql", "databases"]),
        ("rails", ["rails", "ruby"]),
        ("ruby", ["ruby"]),
        ("rust", ["rust"]),
        ("algorithm", ["algorithm"]),
        ("binary search", ["algorithm", "search"]),
        ("二分查找", ["algorithm", "search"]),
        ("selection sort", ["algorithm", "sorting"]),
        ("选择排序", ["algorithm", "sorting"]),
        ("solargraph", ["ruby", "lsp"]),
        ("rubocop", ["ruby", "lsp"]),
        ("zed", ["zed", "lsp"]),
        ("mcp", ["mcp", "ai-coding"]),
        ("tidewave", ["mcp", "ai-coding"]),
        ("周洛华", ["economics", "finance", "sociology"]),
        ("时间游戏", ["economics", "finance", "time"]),
        ("psychology", ["psychology"]),
        ("money", ["finance"]),
        ("wealth", ["finance", "wealth"]),
        ("compounding", ["finance", "compounding"]),
        ("risk", ["finance", "risk"]),
        ("luck", ["finance", "luck"]),
        ("economics", ["economics", "finance"]),
        ("sociology", ["sociology"]),
        ("caching", ["caching"]),
        ("cache", ["caching"]),
        ("time", ["time"]),
        ("young once", ["life", "time", "essay"]),
        ("youth", ["life", "time", "essay"]),
        ("life", ["life"]),
    ]

    type_rules = [
        ("roadmap", ["roadmap"]),
        ("learning", ["learning"]),
        ("guide", ["guide"]),
        ("stage-1", ["guide", "hands-on"]),
        ("hands-on", ["hands-on"]),
        ("q&a", ["qa"]),
        ("cartoon conversation", ["qa"]),
        ("troubleshoot", ["troubleshooting"]),
        ("dns-can-break", ["troubleshooting"]),
        ("deep dive", ["deep-dive"]),
        ("deep-dive", ["deep-dive"]),
        ("advanced", ["advanced"]),
        ("cheatsheet", ["cheatsheet"]),
        ("what happens", ["tutorial"]),
    ]

    for keyword, implied in keyword_rules:
        if keyword in haystack:
            tags.update(implied)

    for keyword, implied in type_rules:
        if keyword in haystack:
            tags.update(implied)

    return sorted(tags)


def add_tags(path: Path, tags: list[str]) -> bool:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines:
        lines = [""]

    if lines[0].strip() == "---":
        end = None
        for index in range(1, len(lines)):
            if lines[index].strip() == "---":
                end = index
                break
        if end is None:
            return False
        if any(re.match(r"^tags:\s*", line, re.IGNORECASE) for line in lines[1:end]):
            return False
        lines.insert(end, f"tags: [{', '.join(tags)}]")
    else:
        lines.insert(0, "---")
        lines.insert(1, f"tags: [{', '.join(tags)}]")
        lines.insert(2, "---")

    new_text = "\n".join(lines)
    if text.endswith("\n"):
        new_text += "\n"
    path.write_text(new_text, encoding="utf-8")
    return True


def autotag_notes(
    paths: list[str],
    notes: list[tuple[Path, list[str]]],
    dry_run: bool = False,
    all_untagged: bool = False,
    strict: bool = False,
) -> int:
    targets: list[Path] = []
    if all_untagged:
        targets = [path for path, tags in notes if not tags]
    else:
        for raw in paths:
            path = Path(raw).expanduser().resolve()
            if not path.is_file():
                print(f"not a file: {raw}")
                return 2
            try:
                path.relative_to(ROOT)
            except ValueError:
                print(f"outside garden: {raw}")
                return 2
            targets.append(path)

    if not targets:
        print("No notes to tag")
        return 0 if all_untagged else 2

    changed = 0
    skipped = 0
    failed = 0
    for path in targets:
        rel = path.relative_to(ROOT)
        existing = parse_tags(path)
        inferred = infer_tags(path)

        if existing:
            print(f"already tagged: {rel} ({', '.join(existing)})")
            skipped += 1
            continue
        if not inferred:
            print(f"could not infer tags: {rel}")
            skipped += 1
            failed += 1
            continue

        verb = "would tag" if dry_run else "tagged"
        print(f"{verb} {rel}: {', '.join(inferred)}")
        changed += 1
        if not dry_run and not add_tags(path, inferred):
            print(f"could not write tags: {rel}")
            failed += 1

    suffix = "would be tagged" if dry_run else "tagged"
    print(f"\n{changed} {suffix}, {skipped} skipped")
    if strict and failed:
        print(f"strict: {failed} note(s) still need manual tags")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Query and regenerate the learning-garden tag system."
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--list", action="store_true", help="list tags with counts")
    group.add_argument("--index", action="store_true", help="regenerate tags/index.md")
    group.add_argument("--untagged", action="store_true", help="list notes without tags")
    group.add_argument("--check", action="store_true", help="exit 1 if any note is untagged")
    parser.add_argument("--tag", action="append", default=[], metavar="TAG", help="filter by tag; repeat for AND matching")
    parser.add_argument("--contains", metavar="TEXT", help="filter by text in title or path")
    parser.add_argument("--dry-run", action="store_true", help="show autotag results without writing")
    parser.add_argument("--all", action="store_true", help="autotag all untagged notes")
    parser.add_argument("--strict", action="store_true", help="fail if any autotag target stays untagged")
    parser.add_argument("command", nargs="?", help="list, index, check, untagged, find, open, autotag, or a tag")
    parser.add_argument("query", nargs="*", help="tags for find; combine with --tag for AND matching")
    args = parser.parse_args()

    notes = [(path, parse_tags(path)) for path in content_files()]

    command = args.command
    if command == "help":
        print_command_help()
        return 0

    if command == "open":
        required_tags = list(args.tag)
        required_tags.extend(args.query)
        required_tags = [normalize_tag(tag) for tag in required_tags if tag]
        matched = []
        for path, tags in notes:
            if required_tags and not all(tag in tags for tag in required_tags):
                continue
            if args.contains:
                rel = path.relative_to(ROOT).as_posix()
                haystack = f"{note_title(path)} {rel}".lower()
                if args.contains.lower() not in haystack:
                    continue
            matched.append(path)
        return open_note(matched)

    if args.list or command == "list":
        list_tags(notes)
        return 0

    if args.index or command == "index":
        write_index(notes)
        return 0

    if args.untagged or command == "untagged":
        untagged = [path for path, tags in notes if not tags]
        for path in untagged:
            print(path.relative_to(ROOT))
        return 0

    if args.check or command == "check":
        untagged = [path for path, tags in notes if not tags]
        for path in untagged:
            print(f"missing tags: {path.relative_to(ROOT)}")
        return 1 if untagged else 0

    if command == "autotag":
        if not args.query and not args.all:
            parser.error("autotag needs a file path or --all")
        return autotag_notes(
            args.query,
            notes,
            dry_run=args.dry_run,
            all_untagged=args.all,
            strict=args.strict,
        )

    required_tags = list(args.tag)
    if command == "find":
        required_tags.extend(args.query)
    elif command:
        required_tags.insert(0, command)
        required_tags.extend(args.query)

    required_tags = [normalize_tag(tag) for tag in required_tags if tag]
    matched = []
    for path, tags in notes:
        if required_tags and not all(tag in tags for tag in required_tags):
            continue
        if args.contains:
            rel = path.relative_to(ROOT).as_posix()
            haystack = f"{note_title(path)} {rel}".lower()
            if args.contains.lower() not in haystack:
                continue
        matched.append((path, tags))

    if not required_tags and not args.contains:
        parser.print_help()
        return 2

    for path, tags in matched:
        print_note(path, tags)
    print(f"\n{len(matched)} note(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
